// Generated by CoffeeScript 1.6.3
/*
 isRTL.coffee
 Copyright (C) 2013 dhilipsiva <dhilipsiva@gmail.com>

 Distributed under terms of the MIT license.
*/


/*
 FIXME: I have added support only for arabic charecters.
 Any Pull request for other characters is greatly appreciated.

 Discussion:
 http://codereview.stackexchange.com/questions/32131/isrtl-coffee-a-javascript-library-to-determine-if-a-text-is-of-right-to-left-d
*/


/*
 Arabic Characters
*/


(function() {
  var reRTL, rtlChars;

  rtlChars = ['\u0600-\u06FF', '\u0750-\u077F', '\uFB50-\uFDFF', '\uFE70-\uFEFF'].join("");

  reRTL = new RegExp("^[" + rtlChars + "]");

  window.isRTL = function(text) {
    return text.match(reRTL);
  };

}).call(this);

/*
//@ sourceMappingURL=isRTL.map
*/
